<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $array=[
            [1,'DZD'],
            [2,'AOA'],
            [3,'ARS'],
            [4,'AMD'],
            [5,'AUD'],
            [6,'EUR'],
            [7,'AZN'],
            [8,'BHD'],
            [9,'BBD'],
            [10,'BYN'],
            [11,'EUR'],
            [12,'BMD'],
            [13,'BOB'],
            [14,'BAM'],
            [15,'BWP'],
            [16,'BRL'],
            [17,'BGN'],
            [18,'CVE'],
            [19,'CAD'],
            [20,'KYD'],
            [21,'XAF'],
            [22,'CLP'],
            [23,'CNY'],
            [24,'COP'],
            [25,'CDF'],
            [26,'XAF'],
            [27,'CRC'],
            [28,'HRK'],
            [29,'EUR'],
            [30,'CZK'],
            [31,'DKK'],
            [32,'DOP'],
            [33,'USD'],
            [34,'EGP'],
            [35,'USD'],
            [36,'XAF'],
            [37,'EUR'],
            [38,'FJD'],
            [39,'EUR'],
            [40,'EUR'],
            [41,'EUR'],
            [42,'GHS'],
            [43,'GIP'],
            [44,'EUR'],
            [45,'DKK'],
            [46,'GTQ'],
            [47,'GBP'],
            [48,'GYD'],
            [49,'HNL'],
            [50,'HKD'],
            [51,'HUF'],
            [52,'ISK'],
            [53,'INR'],
            [54,'IDR'],
            [55,'IQD'],
            [56,'EUR'],
            [57,'IMP'],
            [58,'ILS'],
            [59,'EUR'],
            [60,'XOF'],
            [61,'JMD'],
            [62,'JPY'],
            [63,'KZT'],
            [64,'KES'],
            [65,'KRW'],
            [66,'EUR'],
            [67,'KWD'],
            [68,'KGS'],
            [69,'LAK'],
            [70,'EUR'],
            [71,'LBP'],
            [72,'LYD'],
            [73,'CHF'],
            [74,'EUR'],
            [75,'EUR'],
            [76,'MOP'],
            [77,'MGA'],
            [78,'MWK'],
            [79,'MYR'],
            [80,'MVR'],
            [81,'EUR'],
            [82,'MRU'],
            [83,'MUR'],
            [84,'MXN'],
            [85,'EUR'],
            [86,'MAD'],
            [87,'MZN'],
            [88,'MMK'],
            [89,'NAD'],
            [90,'EUR'],
            [91,'NZD'],
            [92,'NIO'],
            [93,'NGN'],
            [94,'MKD'],
            [95,'NOK'],
            [96,'OMR'],
            [97,'PKR'],
            [98,'ILS'],
            [99,'JOD'],
            [100,'PGK'],
            [101,'PYG'],
            [102,'PEN'],
            [103,'PHP'],
            [104,'PLN'],
            [106,'USD'],
            [107,'RUB'],
            [108,'RWF'],
            [109,'XCD'],
            [110,'SAR'],
            [111,'XOF'],
            [112,'RSD'],
            [113,'SGD'],
            [114,'EUR'],
            [115,'EUR'],
            [116,'ZAR'],
            [117,'EUR'],
            [118,'LKR'],
            [119,'SZL'],
            [120,'SEK'],
            [121,'CHF'],
            [122,'TWD'],
            [123,'TJS'],
            [124,'TZS'],
            [125,'THB'],
            [126,'USD'],
            [127,'TTD'],
            [128,'TND'],
            [129,'UGX'],
            [130,'UAH'],
            [132,'GBP'],
            [133,'USD'],
            [134,'UYU'],
            [135,'UZS'],
            [136,'VEF'],
            [137,'VND'],
            [138,'ZMW'],
            [139,'ZWD'],
            [140,'PAB']
       ];


       foreach ($array as $key => $value):
        $array2[] = [
        'id' => $value[0],
        'currency_iso_code' => $value[1],
        ];
    endforeach ;
DB::table('currency')->insert($array2);
    }
}
