<?php

/* custom routes generated by CRUD */



Route::group(array('prefix' => '', 'as'=>''), function () {

Route::get('sports', ['as'=> 'sports.index', 'uses' => 'SportController@index']);
Route::post('sports', ['as'=> 'sports.store', 'uses' => 'SportController@store']);
Route::get('sports/create', ['as'=> 'sports.create', 'uses' => 'SportController@create']);
Route::put('sports/{sports}', ['as'=> 'sports.update', 'uses' => 'SportController@update']);
Route::patch('sports/{sports}', ['as'=> 'sports.update', 'uses' => 'SportController@update']);
Route::get('sports/{id}/delete', array('as' => 'sports.delete', 'uses' => 'SportController@getDelete'));
Route::get('sports/{id}/confirm-delete', array('as' => 'sports.confirm-delete', 'uses' => 'SportController@getModalDelete'));
Route::get('sports/{sports}', ['as'=> 'sports.show', 'uses' => 'SportController@show']);
Route::get('sports/{sports}/edit', ['as'=> 'sports.edit', 'uses' => 'SportController@edit']);

});



Route::group(array('prefix' => '', 'as'=>''), function () {

Route::get('userPermissions', ['as'=> 'userPermissions.index', 'uses' => 'UserPermissionController@index']);
Route::post('userPermissions', ['as'=> 'userPermissions.store', 'uses' => 'UserPermissionController@store']);
Route::get('userPermissions/create', ['as'=> 'userPermissions.create', 'uses' => 'UserPermissionController@create']);
Route::put('userPermissions/{userPermissions}', ['as'=> 'userPermissions.update', 'uses' => 'UserPermissionController@update']);
Route::patch('userPermissions/{userPermissions}', ['as'=> 'userPermissions.update', 'uses' => 'UserPermissionController@update']);
Route::get('userPermissions/{id}/delete', array('as' => 'userPermissions.delete', 'uses' => 'UserPermissionController@getDelete'));
Route::get('userPermissions/{id}/confirm-delete', array('as' => 'userPermissions.confirm-delete', 'uses' => 'UserPermissionController@getModalDelete'));
Route::get('userPermissions/{userPermissions}', ['as'=> 'userPermissions.show', 'uses' => 'UserPermissionController@show']);
Route::get('userPermissions/{userPermissions}/edit', ['as'=> 'userPermissions.edit', 'uses' => 'UserPermissionController@edit']);

});



Route::group(array('prefix' => '', 'as'=>''), function () {

Route::get('userPermissions', ['as'=> 'userPermissions.index', 'uses' => 'UserPermissionController@index']);
Route::post('userPermissions', ['as'=> 'userPermissions.store', 'uses' => 'UserPermissionController@store']);
Route::get('userPermissions/create', ['as'=> 'userPermissions.create', 'uses' => 'UserPermissionController@create']);
Route::put('userPermissions/{userPermissions}', ['as'=> 'userPermissions.update', 'uses' => 'UserPermissionController@update']);
Route::patch('userPermissions/{userPermissions}', ['as'=> 'userPermissions.update', 'uses' => 'UserPermissionController@update']);
Route::get('userPermissions/{id}/delete', array('as' => 'userPermissions.delete', 'uses' => 'UserPermissionController@getDelete'));
Route::get('userPermissions/{id}/confirm-delete', array('as' => 'userPermissions.confirm-delete', 'uses' => 'UserPermissionController@getModalDelete'));
Route::get('userPermissions/{userPermissions}', ['as'=> 'userPermissions.show', 'uses' => 'UserPermissionController@show']);
Route::get('userPermissions/{userPermissions}/edit', ['as'=> 'userPermissions.edit', 'uses' => 'UserPermissionController@edit']);

});



Route::group(array('prefix' => '', 'as'=>''), function () {

Route::get('userPermissions', ['as'=> 'userPermissions.index', 'uses' => 'UserPermissionController@index']);
Route::post('userPermissions', ['as'=> 'userPermissions.store', 'uses' => 'UserPermissionController@store']);
Route::get('userPermissions/create', ['as'=> 'userPermissions.create', 'uses' => 'UserPermissionController@create']);
Route::put('userPermissions/{userPermissions}', ['as'=> 'userPermissions.update', 'uses' => 'UserPermissionController@update']);
Route::patch('userPermissions/{userPermissions}', ['as'=> 'userPermissions.update', 'uses' => 'UserPermissionController@update']);
Route::get('userPermissions/{id}/delete', array('as' => 'userPermissions.delete', 'uses' => 'UserPermissionController@getDelete'));
Route::get('userPermissions/{id}/confirm-delete', array('as' => 'userPermissions.confirm-delete', 'uses' => 'UserPermissionController@getModalDelete'));
Route::get('userPermissions/{userPermissions}', ['as'=> 'userPermissions.show', 'uses' => 'UserPermissionController@show']);
Route::get('userPermissions/{userPermissions}/edit', ['as'=> 'userPermissions.edit', 'uses' => 'UserPermissionController@edit']);

});



Route::group(array('prefix' => '', 'as'=>''), function () {

Route::get('userPermissions', ['as'=> 'userPermissions.index', 'uses' => 'UserPermissionController@index']);
Route::post('userPermissions', ['as'=> 'userPermissions.store', 'uses' => 'UserPermissionController@store']);
Route::get('userPermissions/create', ['as'=> 'userPermissions.create', 'uses' => 'UserPermissionController@create']);
Route::put('userPermissions/{userPermissions}', ['as'=> 'userPermissions.update', 'uses' => 'UserPermissionController@update']);
Route::patch('userPermissions/{userPermissions}', ['as'=> 'userPermissions.update', 'uses' => 'UserPermissionController@update']);
Route::get('userPermissions/{id}/delete', array('as' => 'userPermissions.delete', 'uses' => 'UserPermissionController@getDelete'));
Route::get('userPermissions/{id}/confirm-delete', array('as' => 'userPermissions.confirm-delete', 'uses' => 'UserPermissionController@getModalDelete'));
Route::get('userPermissions/{userPermissions}', ['as'=> 'userPermissions.show', 'uses' => 'UserPermissionController@show']);
Route::get('userPermissions/{userPermissions}/edit', ['as'=> 'userPermissions.edit', 'uses' => 'UserPermissionController@edit']);

});



Route::group(array('prefix' => '', 'as'=>''), function () {

Route::get('userPermissions', ['as'=> 'userPermissions.index', 'uses' => 'UserPermissionController@index']);
Route::post('userPermissions', ['as'=> 'userPermissions.store', 'uses' => 'UserPermissionController@store']);
Route::get('userPermissions/create', ['as'=> 'userPermissions.create', 'uses' => 'UserPermissionController@create']);
Route::put('userPermissions/{userPermissions}', ['as'=> 'userPermissions.update', 'uses' => 'UserPermissionController@update']);
Route::patch('userPermissions/{userPermissions}', ['as'=> 'userPermissions.update', 'uses' => 'UserPermissionController@update']);
Route::get('userPermissions/{id}/delete', array('as' => 'userPermissions.delete', 'uses' => 'UserPermissionController@getDelete'));
Route::get('userPermissions/{id}/confirm-delete', array('as' => 'userPermissions.confirm-delete', 'uses' => 'UserPermissionController@getModalDelete'));
Route::get('userPermissions/{userPermissions}', ['as'=> 'userPermissions.show', 'uses' => 'UserPermissionController@show']);
Route::get('userPermissions/{userPermissions}/edit', ['as'=> 'userPermissions.edit', 'uses' => 'UserPermissionController@edit']);

});



Route::group(array('prefix' => '', 'as'=>''), function () {

Route::get('userPermissions', ['as'=> 'userPermissions.index', 'uses' => 'UserPermissionController@index']);
Route::post('userPermissions', ['as'=> 'userPermissions.store', 'uses' => 'UserPermissionController@store']);
Route::get('userPermissions/create', ['as'=> 'userPermissions.create', 'uses' => 'UserPermissionController@create']);
Route::put('userPermissions/{userPermissions}', ['as'=> 'userPermissions.update', 'uses' => 'UserPermissionController@update']);
Route::patch('userPermissions/{userPermissions}', ['as'=> 'userPermissions.update', 'uses' => 'UserPermissionController@update']);
Route::get('userPermissions/{id}/delete', array('as' => 'userPermissions.delete', 'uses' => 'UserPermissionController@getDelete'));
Route::get('userPermissions/{id}/confirm-delete', array('as' => 'userPermissions.confirm-delete', 'uses' => 'UserPermissionController@getModalDelete'));
Route::get('userPermissions/{userPermissions}', ['as'=> 'userPermissions.show', 'uses' => 'UserPermissionController@show']);
Route::get('userPermissions/{userPermissions}/edit', ['as'=> 'userPermissions.edit', 'uses' => 'UserPermissionController@edit']);

});
